#!/bin/bash

echo "============================"
stat=`git status | grep "modified"`
if [ -n "$stat" ]
then 
echo "GIT synhronization."
read -p "Input COMMIT: " text
echo "============================"
git add .
git commit -m "$text"
echo "============================"
git push
echo "============================"
git log --oneline -3
echo "============================"
else
echo "Изменений нет !"
echo "============================"
fi
